language: cpp

sudo: required

install:
  - sudo apt-get install cmake clang-tidy
  - cmake --version

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc

script:
  # generating build directory
  - mkdir build
  - cd build
  - cmake .. -DBUILD_DOC=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
  - cp compile_commands.json ..
  - cd ..
  # syntax checking
  - ./syntax_check.sh
  # build project
  - cd build
  - cmake --build .
